grant all privileges on  schema  i2b2metadata to i2b2metadata;
grant all privilieges on all tables in schema public to i2b2demodata; 
grant all privileges on all tables in schema public to i2b2demodata; 
grant all privileges on all tables in schema public to i2b2hive; 
grant all privileges on all tables in schema public to public; 
grant all privileges on all tables in schema pm_hive_data to public; 
grant all privileges on pm_hive_data to public; 
grant all privileges on all tables in schema i2b2pm to public; 
grant no privileges on all tables in schema i2b2pm to public ; 
grant select on all tables in schema i2b2pm to i2b2pm ; 
grant all privileges on all tables in schema i2b2pm to i2b2pm; 
grant all privileges on all tables in schema i2b2hive to i2b2hive; 
grant all privileges on all tables in schema public to i2b2demodata; 
grant all privileges on all tables in schema public to i2b2hivedata; 
grant all privileges on all tables in schema public to i2b2workdata; 
grant all privileges on all tables in schema public to public; 
grant all privileges on qt_query_master to public; 
grant all privileges on qt_query_instance to public; 
grant all privileges on qt_query_master_id_seq to public; 
grant all privileges on qt_query_master_query_master_id_seq to public; 
grant all privileges on qt_query_instance_query_instance_id_seq to public; 
grant all privileges on qt_result_instance_result_instance_id_seq to public; 
grant all privileges on qt_query_result_instance_result_instance_id_seq to public; 
grant all privileges on qt_xml_result_xml_result_id_seq to public; 
grant all privileges on workplace to public; 
grant all privileges on workplace_access to public; 
