FROM jboss/wildfly
ADD i2b2.war /opt/jboss/wildfly/standalone/deployments/
#ADD srv-dstu21.war /opt/jboss/wildfly/standalone/deployments/
ADD pm-ds.xml /opt/jboss/wildfly/standalone/deployments/
ADD ont-ds.xml /opt/jboss/wildfly/standalone/deployments/
ADD crc-ds.xml /opt/jboss/wildfly/standalone/deployments/
ADD workdata-ds.xml /opt/jboss/wildfly/standalone/deployments/

